import { motion, useReducedMotion } from "motion/react";
import { useFlowEnvironment } from "../../app/FlowEnvironmentProvider";
import { selectNowWindow } from "../../domain/life-selectors";

export function NowSpace() {
  const { document, nowCandidates, nowExplanationOpen, dispatchEntityView, focusedEntityId, runCommand, currentTime } = useFlowEnvironment();
  const focusEntity = (id: string) => dispatchEntityView({ type: "entity-view", kind: "recommendation", operation: "select", target: { id } });
  const reducedMotion = useReducedMotion();
  const window = selectNowWindow(document, currentTime);
  const candidates = nowCandidates;
  return <section className="mx-auto w-full max-w-4xl px-4 pb-36 pt-10 sm:px-8" data-now-date={window.dateKey} data-testid="now-space">
    <div className="text-center"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-[#5DE6D4]">Available now{document.calendar.dateKey !== window.dateKey ? " · Today" : ""}</p><motion.div animate={reducedMotion ? { opacity: 1 } : { scale: [0.96, 1.03, 1], opacity: 1 }} className="mx-auto mt-6 grid size-36 place-items-center rounded-full border border-[#2A9E93]/60 bg-[#0E2027]" initial={{ opacity: 0 }} transition={{ duration: reducedMotion ? 0.12 : 0.6 }}><div><strong className="block font-serif text-4xl text-[#8AF5E7]">{window.minutes}</strong><span className="text-xs text-[#A6B3B1]">minutes open</span></div></motion.div><h1 className="mt-7 font-serif text-4xl tracking-[-0.04em]">What fits right now?</h1><p className="mt-3 text-sm text-[#A6B3B1]">Until {window.nextTitle ?? "your day boundary"}</p></div>
    <div className="mt-10 space-y-3">{candidates.map((candidate, index) => <motion.button data-action-id="now.select" animate={{ opacity: 1, y: 0 }} className={`flex min-h-[78px] w-full items-center justify-between rounded-[14px] border p-4 text-left ${focusedEntityId === candidate.id ? "border-[#5DE6D4] bg-[#0E2027]" : "border-[#17343A] bg-[#0A171D]"}`} data-flow-action="Select Now recommendation" initial={reducedMotion ? false : { opacity: 0, y: 8 }} key={candidate.id} onClick={() => focusEntity(candidate.id)} transition={{ delay: reducedMotion ? 0 : index * 0.07 }} type="button"><span><span className="block text-base">{candidate.title}</span><span className="mt-1 block text-xs text-[#70817F]">{candidate.source === "plan-step" ? "Plan step" : candidate.source === "commitment" ? "Commitment" : "Inbox capture"}</span></span><span className="rounded-full border border-[#28535A] px-3 py-2 text-xs text-[#8AF5E7]">{candidate.minutes}m</span></motion.button>)}{!candidates.length && <div className="rounded-[14px] border border-dashed border-[#28535A] p-10 text-center"><p>Nothing useful fits this gap.</p><p className="mt-2 text-sm text-[#70817F]">Keeping the space free is a valid decision.</p></div>}</div>
    <div className="mt-6 flex justify-center gap-2"><button data-action-id="now.explain" className="min-h-11 rounded-full px-4 text-sm text-[#A6B3B1] hover:bg-[#12272E]" data-flow-action="Explain Now recommendations" onClick={() => runCommand("Why these?", "quick")} type="button">Why these?</button><button data-action-id="now.keep-free" className="min-h-11 rounded-full px-4 text-sm text-[#A6B3B1] hover:bg-[#12272E]" data-flow-action="Keep time free" onClick={() => runCommand("Keep the time free", "quick")} type="button">Keep the time free</button></div>
    {nowExplanationOpen && <p className="mx-auto mt-5 max-w-xl rounded-[12px] border border-[#17343A] bg-[#0A171D] p-4 text-center text-sm text-[#A6B3B1]">{candidates.length ? candidates.map(({ title, reason }) => `${title}: ${reason}`).join(" · ") : "No ready item fits the current Calendar window."}</p>}
  </section>;
}
