import { useRef } from "react";
import type { JournalEntry, MemoryArtifact } from "../../../domain/studio-model";
import { useStudioMediaUrl } from "../useStudioMediaUrl";
import { useStudioPlayback } from "../useStudioPlayback";

export function MemoryCompositionView({ memory, entry }: { memory: MemoryArtifact; entry: JournalEntry }) {
  const { url: photoUrl, missing } = useStudioMediaUrl(memory.photoAssetId);
  const { url: audioUrl, state: audioState } = useStudioMediaUrl(entry.audioAssetId);
  const audio = useRef<HTMLAudioElement>(null);
  useStudioPlayback(audio, "memory", memory.id, memory.audioInMs, memory.audioOutMs ?? entry.recordingDurationMs, { url: audioUrl, state: audioState });
  const date = new Intl.DateTimeFormat("en", { dateStyle: "long" }).format(new Date(entry.createdAt));
  const textStyle = { fontSize: `${memory.textScale}em`, transform: `translate(${memory.textOffset.x}px, ${memory.textOffset.y}px)` };

  const audioElement = audioUrl && memory.audioEnabled ? <audio data-action-id="memory.playback" className="mt-6 w-full" controls onTimeUpdate={(event) => { if (memory.audioOutMs !== undefined && event.currentTarget.currentTime * 1000 >= memory.audioOutMs) event.currentTarget.pause(); }} ref={audio} src={audioUrl} /> : null;
  const darkDateClass = memory.datePlacement === "corner" ? "absolute right-7 top-7 text-sm text-[#D8D0C8]" : "mt-12 text-sm text-[#A7AAA4]";
  const pageDateClass = memory.datePlacement === "corner" ? "absolute right-7 top-7 text-sm text-[#806F5D]" : "mt-12 text-sm text-[#806F5D]";
  if (memory.composition === "voice") return <section className="relative grid min-h-[280px] sm:min-h-[420px] xl:min-h-[560px] overflow-hidden rounded-[30px] bg-[#151816] p-8 text-[#F4EFE5] sm:p-12" data-memory-composition="voice"><div className="my-auto"><p className="text-xs uppercase tracking-[0.2em] text-[#7EA7A4]">Voice memory</p><blockquote className="mt-8 max-w-2xl font-serif text-[clamp(2rem,5vw,4.4rem)] leading-[1.08] tracking-[-0.035em]" style={textStyle}>{memory.passage}</blockquote>{memory.showDate && <p className={darkDateClass}>{date}</p>}<div aria-hidden className="mt-12 flex h-16 items-center gap-1">{Array.from({ length: 48 }, (_, index) => <span className="flex-1 rounded-full bg-[#7EA7A4]" key={index} style={{ height: `${16 + (index * 17 % 62)}%`, opacity: 0.35 + (index % 5) / 10 }} />)}</div></div>{audioElement}</section>;
  if (memory.composition === "page") return <section className="relative grid min-h-[280px] sm:min-h-[420px] xl:min-h-[560px] overflow-hidden rounded-[30px] bg-[#EFE6D6] p-8 text-[#27312C] sm:p-14" data-memory-composition="page"><div className="border-l border-[#C67C65] pl-7 sm:pl-12"><p className="text-xs uppercase tracking-[0.2em] text-[#806F5D]">From the journal</p><blockquote className="mt-10 max-w-3xl font-serif text-[clamp(2rem,5vw,4.8rem)] leading-[1.13] tracking-[-0.04em]" style={textStyle}>{memory.passage}</blockquote>{memory.showDate && <p className={pageDateClass}>{date}</p>}</div>{photoUrl && <img alt="Original journal attachment" className="absolute bottom-8 right-8 max-h-40 max-w-[34%] rounded-2xl object-contain" src={photoUrl} />}{missing && <p className="absolute bottom-8 right-8 text-sm text-[#A54E43]">Original photograph unavailable</p>}{audioElement && <div className="absolute bottom-5 left-8 max-w-[45%]">{audioElement}</div>}</section>;
  return <section className="relative min-h-[280px] sm:min-h-[420px] xl:min-h-[560px] overflow-hidden rounded-[30px] bg-[#0C0E0D] text-[#F4EFE5]" data-memory-composition="still">{photoUrl ? <img alt="Original journal attachment" className="absolute inset-0 size-full object-contain opacity-75" src={photoUrl} /> : <div className="absolute inset-0 bg-[#252A26]"/>}<div className="absolute inset-x-7 bottom-9 rounded-[20px] bg-black/55 p-5 sm:inset-x-12 sm:bottom-12 sm:p-7"><blockquote className="max-w-3xl font-serif text-[clamp(1.8rem,4.5vw,4rem)] leading-[1.08] tracking-[-0.035em]" style={textStyle}>{memory.passage}</blockquote>{memory.showDate && memory.datePlacement === "inline" && <p className="mt-7 text-sm text-[#E7DED2]">{date}</p>}{audioElement}</div>{memory.showDate && memory.datePlacement === "corner" && <p className="absolute right-7 top-7 text-sm text-[#E7DED2]">{date}</p>}{missing && <p className="absolute right-5 top-5 rounded-full bg-black/70 px-4 py-2 text-sm">Original photograph unavailable</p>}</section>;
}
