import { groupsWithDeliveryHistory, recentDeliveries } from "./deliveryProjection";
import { useState, type ReactNode } from "react";
import { useFlowEnvironment } from "../../app/FlowEnvironmentProvider";
import type { DeliveryReceipt } from "./messaging";
import { warmButton, warmCard, warmField, warmQuietButton } from "../../shared/design-system/WorldPageShell";
import { allCalendarEvents } from "../../domain/life-calendar-world";
import { formatTime } from "../day-planner/time";
export function FriendsOverview({ receipts, children }: { receipts: readonly DeliveryReceipt[]; children?: ReactNode }) {
  const environment = useFlowEnvironment(), { document } = environment;
  const tab = environment.conversationContext.friendsCollection ?? "Recent";
  const [name, setName] = useState(""), [members, setMembers] = useState<string[]>([]);
  return <section className="my-6" data-page-task="collections" data-task-entity-id={`friends-collection:${tab}`}><nav className="mb-4 flex flex-wrap gap-2" aria-label="Friends collections">{["Recent", "Plans", "Voice notes", "Groups"].map((item) => <button data-action-id="friends.collection" key={item} className={warmQuietButton} aria-pressed={tab === item} type="button" onClick={() => environment.dispatchFriend({ type: "friend-open", collection: item as typeof tab })}>{item}</button>)}</nav><div className={`${warmCard} p-5`}>
    {tab === "Recent" && <>{recentDeliveries(receipts).map(({ id, message, label }) => <button data-action-id="friends.conversation-open" className="mb-4 block w-full text-left" type="button" key={id} onClick={() => environment.dispatchFriend(message.recipient.kind === "group" ? { type: "friend-group", operation: "open", groupId: message.recipient.id } : { type: "friend-person", operation: "open", query: "", resolvedPersonId: message.recipient.id })}><span className="block text-sm">{message.recipientSnapshot?.name ?? "Conversation"} · {message.body || message.attachment?.title}</span><span className="text-xs text-flow-secondary">{label}</span></button>)}{!receipts.length && <p className="text-sm text-flow-secondary">No local deliveries yet.</p>}{children}</>}
    {tab === "Plans" && <>{allCalendarEvents(document).filter((event) => event.participantIds?.length).map((event) => <button data-action-id="calendar.inspect" type="button" key={event.id} className="mb-3 block text-left text-sm" onClick={() => { environment.navigate("today"); environment.setTemporalScope({ kind: "day", dateKey: event.dateKey }); environment.selectCalendarEvent(event.id); }}>{event.title}<span className="block text-xs text-flow-secondary">{event.dateKey} · {formatTime(event.start)}</span></button>)}{!allCalendarEvents(document).some((event) => event.participantIds?.length) && <p className="text-sm text-flow-secondary">No shared Calendar plans yet.</p>}</>}
    {tab === "Voice notes" && <>{document.friends!.voiceNotes.map((note) => <button data-action-id="friends.voice-open" type="button" className="mb-3 block text-left text-sm" key={note.id} onClick={() => environment.dispatchFriend({ type: "friend-voice", operation: "open", noteId: note.id })}>{note.title}<span className="block text-xs text-flow-secondary">{note.createdAt.slice(0, 10)} · {note.status}</span></button>)}{!document.friends!.voiceNotes.length && <p className="text-sm text-flow-secondary">No voice notes yet.</p>}</>}
    {tab === "Groups" && <>{groupsWithDeliveryHistory(document, receipts).map((group) => <button data-action-id="friends.group-open" type="button" className="mb-4 block text-left" key={group.id} onClick={() => environment.dispatchFriend({ type: "friend-group", operation: "open", groupId: group.id })}><span className="font-serif text-xl">{group.name}</span><span className="block text-xs text-flow-secondary">{group.memberIds.length} members · private</span></button>)}<form className="mt-4 space-y-3 border-t border-[#E8E0D7] pt-4" onSubmit={(event) => { event.preventDefault(); if (name.trim() && members.length) { environment.dispatchFriend({ type: "friend-group", operation: "create", name, memberIds: members }); setName(""); setMembers([]); } }}><label className="block text-sm">New private group<input data-action-id="friends.group-create" aria-label="Group name" className={`${warmField} mt-2`} value={name} onChange={(event) => setName(event.target.value)} /></label><fieldset><legend className="mb-2 text-xs text-flow-secondary">Members</legend><div className="flex flex-wrap gap-4">{document.people.filter(({ archived }) => !archived).map((person) => <label className="flex min-h-11 items-center gap-2 text-sm" key={person.id}><input data-action-id="friends.group-create" type="checkbox" checked={members.includes(person.id)} onChange={(event) => setMembers(event.target.checked ? [...members, person.id] : members.filter((id) => id !== person.id))} />{person.name}</label>)}</div></fieldset><button data-action-id="friends.group-create" className={warmButton} type="submit">Create group</button></form></>}
  </div></section>;
}
