import { SharedMemory } from "./SharedMemory";
import { useState, type FormEvent } from "react";
import type { FriendGroup } from "../../domain/friends-model";
import { deliveryDraftLabel, type DeliveryReceipt } from "./messaging";
import { useFlowEnvironment } from "../../app/FlowEnvironmentProvider";
import { warmButton, warmCard, warmField, warmQuietButton } from "../../shared/design-system/WorldPageShell";
import { PersonAvatar } from "./PersonAvatar";
import { messagesForRecipient } from "./deliveryProjection";
import { SharedVoiceNote } from "./SharedVoiceNote";
import { VoiceNoteSpace } from "./VoiceNoteSpace";
import { formatTime } from "../day-planner/time";

export function GroupSpace({ group, receipts }: { group: FriendGroup; receipts: readonly DeliveryReceipt[] }) {
  const environment = useFlowEnvironment(), { document } = environment;
  const [body, setBody] = useState(""), [reply, setReply] = useState(""), [personId, setPersonId] = useState(group.memberIds[0] ?? ""), [response, setResponse] = useState<"in" | "maybe" | "cant" | "alternative">("in");
  const members = document.people.filter(({ id }) => group.memberIds.includes(id));
  const plans = document.friends!.groupPlans.filter(({ groupId }) => groupId === group.id);
  const note = document.friends!.voiceNotes.find(({ id }) => id === environment.conversationContext.activeVoiceNoteId);
  const messages = messagesForRecipient(document, receipts, { kind: "group", id: group.id });
  const draft = (event: FormEvent) => { event.preventDefault(); if (body.trim()) { environment.dispatchFriend({ type: "friend-message", resolvedGroupId: group.id, body }); setBody(""); } };
  return <><button data-action-id="friends.overview" className={warmQuietButton} type="button" onClick={() => environment.runCommand("Open Friends", "quick")}>← All friends</button><div className="my-5 flex flex-wrap gap-3">{members.map((person) => <button data-action-id="friends.person-open" key={person.id} className="flex items-center gap-2 text-sm" type="button" onClick={() => environment.dispatchFriend({ type: "friend-person", operation: "open", query: person.name, resolvedPersonId: person.id })}><PersonAvatar person={person} />{person.name}</button>)}</div>
    {note?.recipient.id === group.id && <VoiceNoteSpace note={note} />}
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><section className={`${warmCard} p-6`} aria-label="Group messages" data-page-task="conversation" data-task-entity-id={group.id}><h2 className="font-serif text-2xl">Conversation</h2><p className="mt-2 text-xs text-flow-secondary">Private · Flow-local in this browser</p>{!group.archived && <form className="mt-5 space-y-3" onSubmit={draft}><label className="block text-xs" htmlFor="group-message">Message to {group.name}</label><textarea data-action-id="friends.message-compose" id="group-message" className={`${warmField} min-h-24`} value={body} onChange={(event) => setBody(event.target.value)} /><div className="flex flex-wrap gap-2"><button data-action-id="friends.message-compose" className={warmButton} type="submit">Review message</button><button data-action-id="friends.voice-create" className={warmQuietButton} type="button" onClick={() => environment.dispatchFriend({ type: "friend-voice", operation: "create", resolvedGroupId: group.id })}>Voice note</button></div></form>}<div className="my-5 divide-y divide-[#E8E0D7]">{messages.map(({ key, message, receipt, restoredDraft }) => <article className="py-4" key={key}><p className="whitespace-pre-wrap text-sm leading-7">{message.body}</p>{!restoredDraft && message.attachment?.kind === "voice" && <SharedVoiceNote message={message} />}{!restoredDraft && message.attachment?.kind === "memory" && <SharedMemory message={message} />}<p className="mt-2 text-xs text-flow-muted">{receipt?.label ?? (restoredDraft ? "Restored draft · delivered message unchanged" : deliveryDraftLabel(message))}</p></article>)}{!messages.length && <p className="text-sm text-flow-secondary">No messages yet.</p>}</div></section>
      <aside className="space-y-4"><section className={`${warmCard} p-5`}><h2 className="font-serif text-xl">Plans</h2>{!plans.length && <p className="mt-3 text-sm text-flow-secondary">Say “Ask {group.name} who's free Saturday afternoon.”</p>}{plans.map((plan) => <div className="mt-4 border-t border-[#E8E0D7] pt-4" key={plan.id}><button data-action-id="friends.group-replies" type="button" className="text-left text-sm font-medium" onClick={() => environment.dispatchFriend({ type: "friend-group", operation: "replies", groupId: group.id, planId: plan.id })}>{plan.title}</button>{plan.options.map((option) => <p className="mt-2 text-xs text-flow-secondary" key={option.id}>{option.dateKey} · {formatTime(option.startMinutes)} · {plan.status === "confirmed" ? "Calendar plan" : "Proposed time"}</p>)}{plan.replies.map((item) => <p className="mt-3 text-sm" key={item.personId}>{members.find(({ id }) => id === item.personId)?.name}: {item.text}<span className="block text-xs text-flow-muted">{item.provenance === "provider" ? "Received reply" : "Reply recorded by you"}</span></p>)}{!plan.replies.length && <p className="mt-3 text-xs text-flow-secondary">No recorded replies. Availability is unknown.</p>}<form className="mt-4 space-y-2" onSubmit={(event) => { event.preventDefault(); if (reply.trim()) { environment.dispatchFriend({ type: "friend-group", operation: "record-reply", groupId: group.id, planId: plan.id, personId, response, value: reply }); setReply(""); } }}><label className="block text-xs">Record a reply you received<select data-action-id="friends.group-record-reply" aria-label="Reply from" className={`${warmField} mt-2`} value={personId} onChange={(event) => setPersonId(event.target.value)}>{members.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label><select data-action-id="friends.group-record-reply" aria-label="Reply response" className={warmField} value={response} onChange={(event) => setResponse(event.target.value as typeof response)}><option value="in">In</option><option value="maybe">Maybe</option><option value="cant">Can't</option><option value="alternative">Another time</option></select><input data-action-id="friends.group-record-reply" aria-label="Actual reply" className={warmField} value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Their actual words" /><button data-action-id="friends.group-record-reply" className={warmQuietButton} type="submit">Record reply</button></form></div>)}</section></aside>
    </div></>;
}
