import { useState, useRef } from "react";
import type { FriendMessage } from "../../domain/friends-model";
import { useFlowEnvironment } from "../../app/FlowEnvironmentProvider";
import { useStudioMediaUrl } from "../studio/useStudioMediaUrl";
import { useStudioPlayback } from "../studio/useStudioPlayback";
import { warmQuietButton, warmField } from "../../shared/design-system/WorldPageShell";
export function SharedMemory({ message }: { message: FriendMessage }) {
  const environment = useFlowEnvironment(), [reply, setReply] = useState("");
  const attachment = message.attachment!, media = useStudioMediaUrl(attachment.assetId);
  const audio = useRef<HTMLAudioElement>(null);
  useStudioPlayback(audio, "voice-note-playback", message.id, 0, attachment.durationMs, media, () => environment.selectRecordingPlayback({ kind: "shared-message", id: message.id }));
  const recipient = message.recipient.kind === "group" ? { resolvedGroupId: message.recipient.id } : { resolvedPersonId: message.authorPersonId ?? message.recipient.id };
  return <section className="my-4 rounded-2xl border border-[#E8E0D7] p-4" aria-label={`Shared Memory: ${attachment.title}`}><h3 className="font-serif text-xl">{attachment.title}</h3>{attachment.mediaType === "image" && media.url && <img className="my-4 max-h-80 w-full object-contain" alt={attachment.title} src={media.url} />}{attachment.mediaType === "audio" && media.url && <audio data-action-id="friends.shared-audio" ref={audio} aria-label={`Memory audio: ${attachment.title}`} controls className="my-4 w-full" src={media.url} />}{attachment.assetId && (media.missing || media.state === "failed") && <p className="mt-3 text-xs text-flow-secondary">This shared media is unavailable on this device.</p>}<p className="mt-3 whitespace-pre-wrap font-serif text-lg leading-8">{attachment.text}</p><div className="mt-4 flex flex-wrap gap-2">{(["heart", "laugh"] as const).map((reaction) => <button data-action-id="friends.memory-react" className={warmQuietButton} type="button" key={reaction} aria-pressed={environment.document.friends!.reactions.some((item) => item.messageId === message.id && item.reaction === reaction && !item.personId)} onClick={() => environment.dispatchFriend({ type: "friend-memory", operation: "react", messageId: message.id, reaction })}>{reaction === "heart" ? "Heart" : "Laugh"}</button>)}<button data-action-id="friends.voice-reply" className={warmQuietButton} type="button" onClick={() => environment.dispatchFriend({ type: "friend-voice", operation: "create", replyToMessageId: message.id, ...recipient })}>Voice reply</button></div><form className="mt-3 flex gap-2" onSubmit={(event) => { event.preventDefault(); if (reply.trim()) { environment.dispatchFriend({ type: "friend-reply", body: reply, replyToMessageId: message.id, ...recipient }); setReply(""); } }}><input data-action-id="friends.message-reply" className={warmField} aria-label={`Reply to ${attachment.title}`} value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Your reply" /><button data-action-id="friends.message-reply" className={warmQuietButton} type="submit">Review reply</button></form><p className="mt-3 text-xs text-flow-muted">Reactions and replies stay Flow-local. Private source material is not linked here.</p></section>;
}
