import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, expect, it } from "vitest";
import { FlowEnvironmentApp } from "./FlowEnvironmentApp";
import { FakeRecognitionAdapter } from "../features/day-planner/voice/fakeRecognition";
import { createFreshLifeSnapshot, LIFE_STORAGE_KEY } from "../domain/life-storage";
import type { LifeSnapshot } from "../domain/life-model";
import { canonicalPerson } from "../features/friends/people";
import { deliveryReceipts } from "../features/friends/messaging";
const at = "2026-09-12T10:00:00Z", now = () => new Date(at);
const read = () => JSON.parse(localStorage.getItem(LIFE_STORAGE_KEY)!) as LifeSnapshot;
beforeEach(() => {
  localStorage.clear(); const snapshot = createFreshLifeSnapshot("2026-09-12");
  snapshot.document.people = ["Sarah Miller", "Sarah Jones", "John"].map((name) => canonicalPerson({ id: name, kind: "person", name, createdAt: at, updatedAt: at }));
  localStorage.setItem(LIFE_STORAGE_KEY, JSON.stringify(snapshot)); window.history.replaceState({}, "", "/people");
  Object.defineProperty(navigator, "locks", { configurable: true, value: { request: async (_key: string, options: unknown, task?: () => Promise<unknown>) => typeof options === "function" ? options() : task!() } });
});
it.each(["typed", "voice"] as const)("clarifies members and time, records actual replies, and confirms one Calendar plan through %s", async (mode) => {
  const adapter = new FakeRecognitionAdapter(); render(<FlowEnvironmentApp now={now} recognitionAdapter={adapter} />); await waitFor(() => expect(adapter.startCount).toBe(1)); let seq = 0;
  const command = async (text: string) => { if (mode === "voice") await act(async () => adapter.emitFinal(text, `group-${++seq}`)); else { if (!screen.queryByLabelText("Tell Flow what to change")) fireEvent.click(screen.getByRole("button", { name: "Open Flow command" })); const field = screen.getByLabelText("Tell Flow what to change"); fireEvent.change(field, { target: { value: text } }); fireEvent.submit(field.closest("form")!); } await waitFor(() => expect(document.querySelector("[data-last-transcript]")).toHaveAttribute("data-last-transcript", text)); };
  await command("Create a group called Barcelona with Sarah and John"); expect(document.body.textContent).toContain("Which Sarah?"); expect(read().document.friends?.groups).toHaveLength(0);
  await command("Sarah Miller"); await waitFor(() => expect(read().document.friends?.groups).toHaveLength(1)); expect(read().document.friends?.groups[0]?.memberIds).toEqual(["Sarah Miller", "John"]);
  await command("Open Friends"); await command("Open Barcelona"); expect(screen.getByRole("heading", { name: "Barcelona", level: 2 })).toBeInTheDocument();
  await command("Ask Barcelona who's free Saturday"); expect(document.body.textContent).toContain("What time should I ask about?");
  await command("Afternoon"); await waitFor(() => expect(read().document.friends?.groupPlans).toHaveLength(1)); expect(read().document.friends?.groupPlans[0]?.replies).toEqual([]); expect(deliveryReceipts()).toHaveLength(0);
  const invitation = read().document.friends!.messages[0]!;
  expect(invitation.body).toMatch(/Sat.*Sep 19.*afternoon/);
  expect(document.body.textContent).toContain(invitation.body);
  await command("yes"); await waitFor(() => expect(deliveryReceipts()).toHaveLength(1));
  expect(deliveryReceipts()[0]?.message.body).toBe(invitation.body);
  await command("Who replied?"); expect(document.body.textContent).toContain("Nobody's availability is assumed");
  await command("Record Sarah Miller's reply: I can come after four");
  await waitFor(() => expect(read().document.friends?.groupPlans[0]?.replies).toHaveLength(1));
  expect(read().document.friends?.groupPlans[0]?.replies[0]).toMatchObject({ personId: "Sarah Miller", text: "I can come after four", provenance: "recorded-by-user" });
  await command("Who replied?"); expect(document.body.textContent).toContain("Sarah Miller: I can come after four");
  const before = read().past.length; await command("Saturday at five then"); expect(read().past).toHaveLength(before); expect(document.body.textContent).toContain("Book this and deliver the message locally?");
  await command("yes"); await waitFor(() => expect(deliveryReceipts()).toHaveLength(2));
  const final = read(); expect(final.past).toHaveLength(before + 1); expect(final.document.friends?.groupPlans[0]?.status).toBe("confirmed");
  const events = Object.values(final.document.calendars).flatMap(({ events }) => events); expect(events.find(({ title }) => title === "Plan with Barcelona")).toMatchObject({ start: 1020, participantIds: ["Sarah Miller", "John"] });
});
