import type { LifeContext } from "../../domain/life-model";
import type { GlobalIntent } from "./globalInterpreter";
import { captureUiActions, primaryWorldUiActions } from "./uiActionDescriptors";

/** Preserved legacy phrase regressions, not a control-coverage or parity gate. */
export const visibleControlExamples: readonly { label: string; phrase: string; context: LifeContext; expectedType: GlobalIntent["type"]; semanticActionId?: string }[] = [
  { label: "Delete entry", phrase: "Delete entry", context: { route: "journal", topic: "journal", activeJournalEntryId: "journal-1" }, expectedType: "journal-delete", semanticActionId: "studio.journal-delete" },
  { label: "Open Calendar date", phrase: primaryWorldUiActions.today.openDate.phrase, context: { route: "calendar" }, expectedType: "temporal", semanticActionId: primaryWorldUiActions.today.openDate.id },
  { label: "Journal", phrase: "Journal", context: { route: "home" }, expectedType: "navigate" },
  { label: "Atmosphere", phrase: "Atmosphere", context: { route: "home" }, expectedType: "navigate" },
  { label: "Memories", phrase: "Memories", context: { route: "home" }, expectedType: "navigate" },
  { label: "New entry", phrase: "New entry", context: { route: "journal", topic: "journal" }, expectedType: "journal-create" },
  { label: "Start with my voice", phrase: "Start with my voice", context: { route: "journal", topic: "journal" }, expectedType: "journal-create" },
  { label: "Shape sound", phrase: "Shape sound", context: { route: "journal", topic: "journal" }, expectedType: "navigate" },
  { label: "Enter the atmosphere", phrase: "Enter the atmosphere", context: { route: "atmosphere", topic: "atmosphere" }, expectedType: "atmosphere-play" },
  { label: "Return to Journal", phrase: "Return to Journal", context: { route: "atmosphere", topic: "atmosphere" }, expectedType: "navigate" },
  { label: "Open Journal", phrase: "Open Journal", context: { route: "memories", topic: "memory" }, expectedType: "navigate" },
  { label: "Go to Journal", phrase: "Go to Journal", context: { route: "memories", topic: "memory" }, expectedType: "navigate" },
  { label: "Put this in motion", phrase: "Put this in motion", context: { route: "good-to-know", topic: "recommendation", selectedInsightId: "clear-focus-window" }, expectedType: "instinct-act" },
  { label: "See the week in Today", phrase: "See the week in Today", context: { route: "home", topic: "calendar" }, expectedType: "navigate-temporal" },
  { label: "See full day", phrase: "See full day", context: { route: "home", topic: "calendar" }, expectedType: "navigate" },
  { label: "Home", phrase: "Home", context: { route: "calendar" }, expectedType: "navigate" },
  { label: "Undo", phrase: "Undo", context: { route: "home" }, expectedType: "history" },
  { label: "Redo", phrase: "Redo", context: { route: "home" }, expectedType: "history" },
  { label: "What needs me now?", phrase: "What needs me now?", context: { route: "home" }, expectedType: "query-now" },
  { label: captureUiActions.turnIntoOutcome.label, phrase: captureUiActions.turnIntoOutcome.phrase, context: { route: "inbox", selected: { id: "capture-1", kind: "capture", at: 1 } }, expectedType: "capture-convert", semanticActionId: captureUiActions.turnIntoOutcome.id },
  { label: captureUiActions.scheduleTomorrow.label, phrase: captureUiActions.scheduleTomorrow.phrase, context: { route: "inbox", selected: { id: "capture-1", kind: "capture", at: 1 } }, expectedType: "capture-convert-event", semanticActionId: captureUiActions.scheduleTomorrow.id },
  { label: captureUiActions.keepAsNote.label, phrase: captureUiActions.keepAsNote.phrase, context: { route: "inbox", selected: { id: "capture-1", kind: "capture", at: 1 } }, expectedType: "capture-archive", semanticActionId: captureUiActions.keepAsNote.id },
  { label: captureUiActions.keepAllAsNotes.label, phrase: captureUiActions.keepAllAsNotes.phrase, context: { route: "inbox" }, expectedType: "capture-batch-archive", semanticActionId: captureUiActions.keepAllAsNotes.id },
  { label: "Bookmark here", phrase: "Bookmark here", context: { route: "journal", topic: "journal", activeJournalEntryId: "journal-1", voiceMode: "journal-longform" }, expectedType: "journal-bookmark" },
  { label: "Bookmark selection", phrase: "Bookmark selection", context: { route: "journal", topic: "journal", activeJournalEntryId: "journal-1" }, expectedType: "journal-bookmark" },
  { label: "Save entry", phrase: "Save entry", context: { route: "journal", topic: "journal", activeJournalEntryId: "journal-1" }, expectedType: "journal-save" },
  { label: "Start recording", phrase: "Start recording", context: { route: "journal", topic: "journal", activeJournalEntryId: "journal-1" }, expectedType: "journal-recording" },
  { label: "Pause recording", phrase: "Pause recording", context: { route: "journal", topic: "journal", activeJournalEntryId: "journal-1" }, expectedType: "journal-recording" },
  { label: "Resume recording", phrase: "Resume recording", context: { route: "journal", topic: "journal", activeJournalEntryId: "journal-1" }, expectedType: "journal-recording" },
  { label: "Stop recording", phrase: "Stop recording", context: { route: "journal", topic: "journal", activeJournalEntryId: "journal-1" }, expectedType: "journal-recording" },
  { label: "Retry saving recording", phrase: "Retry saving recording", context: { route: "journal", topic: "journal", activeJournalEntryId: "journal-1" }, expectedType: "journal-recording" },
  { label: "Make a memory", phrase: "Make a memory", context: { route: "journal", topic: "journal", activeJournalEntryId: "journal-1" }, expectedType: "memory-create" },
  { label: "Prepare for Maya", phrase: "Prepare for Maya", context: { route: "people", topic: "person", peopleView: "default" }, expectedType: "person-query" },
  { label: "Why this?", phrase: "Why this?", context: { route: "good-to-know", topic: "recommendation", selectedInsightId: "clear-focus-window" }, expectedType: "instinct-why" },
  { label: "Pause", phrase: "Pause", context: { route: "atmosphere", topic: "atmosphere" }, expectedType: "atmosphere-playback" },
  { label: "Resume", phrase: "Resume", context: { route: "atmosphere", topic: "atmosphere" }, expectedType: "atmosphere-playback" },
  { label: "Mute", phrase: "Mute", context: { route: "atmosphere", topic: "atmosphere" }, expectedType: "atmosphere-playback" },
  { label: "Save", phrase: "Save", context: { route: "atmosphere", topic: "atmosphere" }, expectedType: "atmosphere-save" },
  { label: "Duplicate", phrase: "Duplicate", context: { route: "atmosphere", topic: "atmosphere" }, expectedType: "atmosphere-save" },
  { label: "Play Sunday evening", phrase: "Play Sunday evening", context: { route: "atmosphere", topic: "atmosphere" }, expectedType: "atmosphere-play" },
  { label: "Less rain", phrase: "Less rain", context: { route: "atmosphere", topic: "atmosphere" }, expectedType: "atmosphere-adjust" },
  { label: "Larger", phrase: "Larger", context: { route: "memories", topic: "memory", activeMemoryId: "memory-1" }, expectedType: "memory-update" },
  { label: "Smaller", phrase: "Smaller", context: { route: "memories", topic: "memory", activeMemoryId: "memory-1" }, expectedType: "memory-update" },
  { label: "Move up", phrase: "Move up", context: { route: "memories", topic: "memory", activeMemoryId: "memory-1" }, expectedType: "memory-update" },
  { label: "Move down", phrase: "Move down", context: { route: "memories", topic: "memory", activeMemoryId: "memory-1" }, expectedType: "memory-update" },
  { label: "Play", phrase: "Play", context: { route: "memories", topic: "memory", activeMemoryId: "memory-1" }, expectedType: "memory-playback" },
  { label: "Pause", phrase: "Pause", context: { route: "memories", topic: "memory", activeMemoryId: "memory-1" }, expectedType: "memory-playback" },
  { label: "Restart", phrase: "Restart", context: { route: "memories", topic: "memory", activeMemoryId: "memory-1" }, expectedType: "memory-playback" },
  { label: "Date in corner", phrase: "Date in corner", context: { route: "memories", topic: "memory", activeMemoryId: "memory-1" }, expectedType: "memory-update" },
  { label: "Date below words", phrase: "Date below words", context: { route: "memories", topic: "memory", activeMemoryId: "memory-1" }, expectedType: "memory-update" },
  { label: "Remove photo", phrase: "Remove photo", context: { route: "memories", topic: "memory", activeMemoryId: "memory-1" }, expectedType: "memory-update" },
  { label: "Restore photo", phrase: "Restore photo", context: { route: "memories", topic: "memory", activeMemoryId: "memory-1" }, expectedType: "memory-update" },
  { label: "Save memory", phrase: "Save memory", context: { route: "memories", topic: "memory", activeMemoryId: "memory-1" }, expectedType: "memory-save" },
  { label: "Start the voice in 5 seconds earlier", phrase: "Start the voice in 5 seconds earlier", context: { route: "memories", topic: "memory", activeMemoryId: "memory-1" }, expectedType: "memory-audio-trim" },
  { label: "Start the voice in 5 seconds later", phrase: "Start the voice in 5 seconds later", context: { route: "memories", topic: "memory", activeMemoryId: "memory-1" }, expectedType: "memory-audio-trim" },
  { label: "Move the voice out 5 seconds earlier", phrase: "Move the voice out 5 seconds earlier", context: { route: "memories", topic: "memory", activeMemoryId: "memory-1" }, expectedType: "memory-audio-trim" },
  { label: "Move the voice out 5 seconds later", phrase: "Move the voice out 5 seconds later", context: { route: "memories", topic: "memory", activeMemoryId: "memory-1" }, expectedType: "memory-audio-trim" },
  { label: "Complete commitment", phrase: primaryWorldUiActions.commitments.complete("Proposal", "Maya").phrase, context: { route: "people", peopleView: "commitments" }, expectedType: "commitment-complete", semanticActionId: primaryWorldUiActions.commitments.complete("Proposal", "Maya").id },
  { label: "Complete outcome", phrase: primaryWorldUiActions.outcomes.complete.phrase, context: { route: "plans", activePlanId: "plan-1" }, expectedType: "plan-status", semanticActionId: primaryWorldUiActions.outcomes.complete.id },
  { label: "Protect or unprotect event", phrase: primaryWorldUiActions.today.protectEvent("Deep work — project brief").phrase, context: { route: "calendar" }, expectedType: "calendar", semanticActionId: primaryWorldUiActions.today.protectEvent("Deep work — project brief").id },
];
