export const tokens = {
  page: "min-h-dvh bg-flow-page text-flow-ink antialiased selection:bg-flow-blue/15",
  shell: "mx-auto flex min-h-dvh w-full max-w-[1440px] flex-col overflow-hidden bg-flow-page",
  divider: "border-[#E7E0D9]",
  surface: "bg-flow-page",
  raisedSurface: "bg-flow-elevated",
  accentSurface: "bg-flow-blue-soft",
  titleText: "text-flow-ink",
  secondaryText: "text-[#52606D]",
  mutedText: "text-[#8A9097]",
  brandMark: "grid size-8 shrink-0 place-items-center rounded-xl border border-[#CFE0FA] bg-flow-blue-soft text-sm font-bold text-[#4D91F5]",
  eyebrow: "text-[#4D91F5]",
  panel: "rounded-[20px] border border-[#E8E1DA] bg-flow-elevated shadow-[0_14px_38px_rgba(35,43,55,0.05)]",
  quietPanel: "rounded-[18px] border border-[#E8E1DA] bg-flow-elevated",
  focusRing: "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-flow-blue focus-visible:ring-offset-2 focus-visible:ring-offset-flow-page",
  iconButton: "grid size-11 place-items-center rounded-full border border-[#E3DCD5] bg-white text-[#66717D] transition hover:bg-flow-neutral-soft hover:text-flow-ink disabled:cursor-not-allowed disabled:opacity-30",
  primaryButton: "inline-flex min-h-11 items-center justify-center rounded-full bg-flow-ink px-4 text-sm font-semibold text-white transition hover:bg-[#26384F] disabled:cursor-not-allowed disabled:opacity-45",
  textButton: "inline-flex min-h-11 items-center justify-center rounded-full px-3 text-sm font-medium text-[#52606D] transition hover:bg-white hover:text-flow-ink",
  accent: "text-[#4D91F5]",
  muted: "text-[#8A9097]",
  secondary: "text-[#52606D]",
  event: {
    base: "relative rounded-[18px] border px-3.5 py-3 text-left transition-[border-color,background-color,box-shadow,opacity,transform] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-flow-blue focus-visible:ring-offset-2 focus-visible:ring-offset-flow-page",
    neutral: "border-[#DDD7D0] bg-flow-elevated text-flow-ink",
    red: "border-[#E9B8B4] bg-[#FFF0EE] text-[#872E2B]",
    orange: "border-[#EBC9A7] bg-flow-orange-soft text-[#8B5422]",
    yellow: "border-[#E7D49F] bg-[#FFF9E6] text-[#715915]",
    green: "border-[#B8DCCB] bg-[#EEF8F2] text-[#276D50]",
    cyan: "border-[#B9DDD9] bg-[#EFF9F7] text-[#276E67]",
    blue: "border-[#BED4F4] bg-flow-blue-soft text-[#245D9C]",
    indigo: "border-[#D0C5EE] bg-flow-violet-soft text-[#59458B]",
    focused: "border-flow-blue shadow-[0_14px_34px_rgba(77,145,245,0.13)]",
    ghost: "border-dashed opacity-45",
    doneLabel: "text-flow-green-strong",
    meta: "text-flow-secondary",
    fixedIcon: "text-[#4D91F5]",
    protectedIcon: "text-[#B77A25]",
    mooring: "bg-flow-orange/35",
    anchoredRing: "ring-1 ring-flow-orange/35",
    changed: "-translate-y-0.5 shadow-[0_18px_44px_rgba(35,43,55,0.1)]",
    quickShell: "border-[#E3DCD5] bg-white shadow-[0_10px_24px_rgba(35,43,55,0.1)]",
    quickButton: "text-[#52606D] hover:bg-flow-neutral-soft hover:text-flow-ink",
    completeButton: "text-[#52606D] hover:bg-[#EEF8F2] hover:text-flow-green-strong",
    resizeHandle: "text-[#8A9097] hover:bg-flow-blue-soft hover:text-[#4D91F5]",
    colorWash: "bg-current/10",
    lineage: "text-[#4D91F5]",
    liveValue: "border-[#BED4F4] bg-white text-[#245D9C] shadow-[0_8px_22px_rgba(35,43,55,0.08)]",
  },
  state: { tide: "text-[#4D91F5]", protected: "text-[#B77A25]", danger: "text-[#C75151]", success: "text-flow-green-strong", fixed: "text-[#4D91F5]" },
  command: {
    shell: "fixed inset-x-3 bottom-3 z-50 mx-auto max-w-2xl rounded-[22px] border border-[#E8E1DA] bg-flow-elevated p-2 shadow-[0_18px_60px_rgba(35,43,55,0.12)] sm:bottom-5 sm:rounded-full",
    collapsedShell: "fixed bottom-3 right-3 z-50 flex items-center gap-1 rounded-full border border-[#E8E1DA] bg-flow-elevated p-1.5 shadow-[0_18px_60px_rgba(35,43,55,0.12)] sm:bottom-5 sm:right-5",
    open: "grid size-11 place-items-center rounded-full text-[#4D91F5] transition hover:bg-flow-blue-soft focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-flow-blue",
    input: "min-w-0 flex-1 bg-transparent px-3 text-sm text-flow-ink outline-none placeholder:text-flow-muted sm:text-base",
    mic: "grid size-11 shrink-0 place-items-center rounded-full bg-flow-ink text-white transition-transform hover:scale-[1.03] active:scale-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-flow-blue",
    spark: "border-[#BED4F4] text-[#4D91F5]", helper: "text-[#52606D]", heard: "text-[#8A9097]", retry: "text-[#245D9C]", dismiss: "border-[#E3DCD5] bg-white text-[#52606D] hover:bg-flow-neutral-soft hover:text-flow-ink",
  },
  feedback: { base: "shadow-[0_18px_45px_rgba(35,43,55,0.1)]", calm: "border-[#BED4F4] bg-flow-blue-soft", issue: "border-[#E9B8B4] bg-[#FFF0EE]" },
  timeline: {
    spine: "bg-[#DED8D1]", hour: "text-flow-secondary", hourDot: "border-[#CFC7BF] bg-flow-page", grid: "bg-[#E7E0D9]", nowDot: "bg-[#4D91F5] shadow-[0_0_14px_rgba(77,145,245,0.3)]", nowLine: "bg-flow-blue/25", nowText: "text-[#245D9C]", boundary: "text-[#C75151]", boundaryDot: "bg-[#C75151]", boundaryLine: "border-[#C75151]/55", tideMarker: "text-[#4D91F5]", tideLine: "bg-flow-blue/45", tidePath: "stroke-flow-blue/55", origin: "border-flow-blue/25 bg-flow-blue-soft/45", done: "text-flow-green-strong", doneDot: "border-flow-green-strong bg-flow-page",
  },
  breathingRoom: { block: "text-[#245D9C]", dot: "bg-[#4D91F5] shadow-[0_0_16px_rgba(77,145,245,0.25)]", line: "bg-flow-blue/40", pulse: "border border-flow-blue/55 bg-flow-blue-soft shadow-[0_0_12px_rgba(77,145,245,0.16)]", duration: "text-flow-secondary" },
  density: { calm: "border-[#B8DCCB] bg-[#EEF8F2] text-[#276D50]", tight: "border-[#E7D49F] bg-[#FFF9E6] text-[#715915]", overloaded: "border-[#E9B8B4] bg-[#FFF0EE] text-[#872E2B]" },
  living: {
    app: "min-h-dvh bg-flow-page text-flow-ink selection:bg-flow-blue/15", header: "border-[#E7E0D9] bg-flow-page/95", panel: "border border-[#E8E1DA] bg-flow-elevated", panelRaised: "border border-[#DCD4CC] bg-white", activePanel: "border border-flow-blue bg-flow-blue-soft", primary: "text-flow-ink", secondary: "text-[#52606D]", tertiary: "text-[#8A9097]", flow: "text-[#4D91F5]", flowBright: "text-[#245D9C]", protected: "text-[#B77A25]", danger: "text-[#C75151]", hover: "hover:bg-flow-neutral-soft", focusRing: "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-flow-blue focus-visible:ring-offset-2 focus-visible:ring-offset-flow-page", commandDock: "border border-[#E8E1DA] bg-flow-elevated/95 text-flow-ink shadow-[0_16px_44px_rgba(35,43,55,0.08)]",
  },
} as const;

export const livingColors = { flow: "#4D91F5", flowBright: "#245D9C" } as const;

export const motionTokens = { immediateMs: 120, microMs: 240, paintMs: 380, moveMs: 640, reflowMs: 820, replayMaxMs: 2500 } as const;
